name: egywander
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  uuid: ^4.5.1
  crypto: 3.0.6
  provider: ^6.0.5
  shared_preferences: ^2.0.9
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  animate_do: ^3.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: egy
      fonts:
        - asset: assets/fonts/Azonix.otf
    - family: Historic
      fonts:
        - asset: assets/fonts/Historic.otf

  assets:
    - assets/images/welcomescreen.jpg
    - assets/images/welcomescreen1.jpg
    - assets/images/welcomescreen2.jpg
    - assets/images/welcomescreen3.jpg
    - assets/images/welcomescreen4.jpg
    - assets/images/pyramids.jpg
    - assets/images/sizzlereg.jpeg
